sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zsh018062121
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKPcCVDvMsQTANgpxFc
    access-key-secret: cg9c6xobnLEnA9jqGFoQKLyQ1K18Uz
    bucket-name: sky-itcast-zeng
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx03c45078915052f8
    secret: cb1867df081d36e9dd3e505392af204a
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: /Users/zengshuhan/Desktop/sky-take-out/sky-server/src/main/resources/privateKey.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: Desktop/sky-take-out/sky-server/src/main/resources/wechatPay.pem
    notifyUrl: https://6561939e.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://6561939e.r2.cpolar.top/notify/refundSuccess