sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zsh018062121
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKPcCVDvMsQTANgpxFc
    access-key-secret: cg9c6xobnLEnA9jqGFoQKLyQ1K18Uz
    bucket-name: sky-itcast-zeng
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx03c45078915052f8
    secret: cb1867df081d36e9dd3e505392af204a